name: newman

on:
  push:
    branches:
      - main

jobs:
  newman_test:
    runs-on:
      ubuntu-latest
      # Service containers to run with `container-job`
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/mydb
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Run migration
        run: npx prisma migrate deploy

      - name: Run Application
        run: yarn build && yarn start:prod

      - name: newman install
        if: contains(github.event_name, 'push')
        run: sudo npm install -g newman

      - name: E2E Tests
        if: contains(github.event_name, 'push')
        run: ./run-api-tests.sh
        env:
          APIURL: http://localhost:3000/api
