name: newman

on:
  push:
    branches:
      - main

jobs:
  newman_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Run Application
        run: yarn build && yarn start:prod

      - name: newman install
        if: contains(github.event_name, 'push')
        run: sudo npm install -g newman

      - name: E2E Tests
        if: contains(github.event_name, 'push')
        run: ./run-api-tests.sh
        env:
          APIURL: http://localhost:3000/api
