name: newman

on:
  push:
    branches:
      - master
jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: newman install
        if: contains(github.event_name, 'push')
        run: sudo npm install -g newman

      - name: E2E Tests
        if: contains(github.event_name, 'push')
        run APIURL=http://localhost:3000/api ./run-api-tests.sh

      - name: Cleanup
        if: always()
        run: rm -f ./api.json
